name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "pre-release"]

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag and update .version file
        id: latest-tag
        run: |
          git fetch --tags

          latestTag=$(git tag --sort=-creatordate | head -n 1)

          echo "Latest tag: $latestTag"

          # Set GitHub Actions variables
          echo "version=$latestTag" >> $GITHUB_OUTPUT
          echo "VERSION=$latestTag" >> $GITHUB_ENV

          # Update .version file
          echo "${VERSION}" > .version
          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Verify version
        run: |
          echo "Version: ${VERSION}"
          cat .version
