name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "pre-release"]

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

        echo "CREATED=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_OUTPUT"
    - name: Get latest tag
      run: |
        cd legacy
        echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
    
    - name: Print version
      run: |
        echo "Version: $VERSION"
